name: Auto Merge

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Automerge PR
      #if: contains(github.event.pull_request.labels.*.name, 'ready to merge') && github.event.pull_request.reviews.approved >= 2
      uses: actions/merge-pull-request@v2
      with:
        message: 'This PR is ready to be merged'
