name: Auto Merge

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, update]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Automatically Merge PR
      uses: plm9606/automerge_actions@1.2.2
      with:
        # The label name to automatically merge. Default is "automerge".
        label-name: "*"
        # The number of reviewers to automatically merge. Default is 1.
        reviewers-number: 0
        # The merge method ("merge", "squash", "rebase"). Default is "merge"
        merge-method: "squash"
        # Let the bot delete the merged branch. true or false.
        auto-delete: true
        # GitHub WebHook Secret Token
        github-token: ${{ secrets.GITHUB_TOKEN }}

